# Generated by Django 4.2.5 on 2023-09-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0003_yourmodel_remove_case_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
