# Generated by Django 4.2.5 on 2023-09-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0004_delete_yourmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('closed', 'Closed'), ('open', 'Open')], default='pending', max_length=20),
        ),
    ]
